### PR TITLE
update init file

### PR DESCRIPTION
**Pull request by lilawren**
Related to Issue: ImportError: No module named 'version' #20

### CODE REVIEW

**Comment by StephNelsonMTA** [comment]
Hi –

I recently got a new workstation and have resinstalled everything. However, now I am getting a ton of error messages and can’t seem to figure out how to fix this. Can you help?

___

C:\Python27\ArcGIS10.3\python.exe G:/03_Geodata/DatabaseAdministration/scripts/arcpy.py
Traceback (most recent call last):
  File "G:/03_Geodata/DatabaseAdministration/scripts/arcpy.py", line 1, in <module>
    import arcpy
  File "G:\03_Geodata\DatabaseAdministration\scripts\arcpy.py", line 2, in <module>
    import arcpy_metadata
  File "C:\Python27\ArcGIS10.3\lib\site-packages\arcpy_metadata\__init__.py", line 4, in <module>
    from arcpy_metadata.metadata_editor import MetadataEditor
  File "C:\Python27\ArcGIS10.3\lib\site-packages\arcpy_metadata\metadata_editor.py", line 42, in <module>
    installDir = arcpy.GetInstallInfo("desktop")["InstallDir"]
AttributeError: 'module' object has no attribute 'GetInstallInfo'

Process finished with exit code 1


---

Thanks,
Steph

**Comment by thomas-maschler** [comment]
That's odd. 
if you run python in a shell (ie IDLE) can you execute the following command

```python
import arcpy
arcpy.GetInstallInfo("desktop")["InstallDir"]
```

If not there must be something wrong with your arcpy installation

**Comment by StephNelsonMTA** [comment]
Yes, I can run that –
[cid:image001.png@01D1F6DF.8F7D52B0]

**Comment by nickrsan** [comment]
I think I see what's going on. Steph, it looks like maybe the script you
are running is named arcpy too? That's going to cause a namespace
collision, and instead of running the functions from ArcGIS' arcpy, it's
going to look in your Python file and give you errors that the functions
don't exist (like this one). Try renaming your script to something else and
running again.

-Nick <nick@enviroconsumer.org>

**Comment by StephNelsonMTA** [comment]
Dang, tried that – no dice!

**Comment by nickrsan** [comment]
Is it still giving you the same traceback, even after renaming arcpy.py to
something_else.py (or whatever you named it)? Or is the message different?
Thanks!

-Nick <nick@enviroconsumer.org>

**Comment by nickrsan** [comment]
Also, if it is the same traceback, would you be able to send us the full
folder of this script (at least, anything that's a Python script in that
folder) so we can take a look?

Another thing to try on the command line, since Thomas' suggestion of
running GetInstallInfo worked before there - would be to try to run "import
arcpy_metadata" there - that will tell you if you have an issue with your
particular script, or your arcpy_metadata installation (in most cases).

Thanks!

-Nick <nick@enviroconsumer.org>

**Comment by StephNelsonMTA** [comment]
Hi – it’s still giving me the same error message:

C:\Python27\ArcGIS10.3\python.exe G:/03_Geodata/DatabaseAdministration/scripts/Thing1.py
Traceback (most recent call last):
  File "G:/03_Geodata/DatabaseAdministration/scripts/Thing1.py", line 1, in <module>
    import arcpy
  File "G:\03_Geodata\DatabaseAdministration\scripts\arcpy.py", line 2, in <module>
    arcpy.GetInstallInfo()
AttributeError: 'module' object has no attribute 'GetInstallInfo'

Process finished with exit code 1

**Comment by nickrsan** [comment]
Hi Steph,

It looks like there's still a file named arcpy.py in that folder that it's
importing. It's possible that this is the precompiled "arcpy.pyc" and it's
loading it, thinking there's still a module named arcpy there. If you see a
file with that name in the folder, you should delete it.

-Nick <nick@enviroconsumer.org>

**Comment by thomas-maschler** [comment]
If you look at the traceback it still tries to look for the module your arcpy.py, not the actual arcpy module.

File "G:\03_Geodata\DatabaseAdministration\scripts\arcpy.py", line 2, in <module>
    arcpy.GetInstallInfo()

Does the arcpy.py file still exist in the listed folder? If yes, rename it into something else or delete it.
Python always checks the local path first when importing a module and will get confused

**Comment by StephNelsonMTA** [comment]
Hi Nick:

Alright, I seem to be able to run ‘import arcpy_metadata’ just fine in the shell but not in the IDE I’m using (Pycharm). Also, wrote a very simple script here just to limit the potential source of error, so all I’m doing is importing arcpy and arcpy_metadata – take a look:

[cid:image002.png@01D1F6E5.589AF8F0]

**Comment by StephNelsonMTA** [comment]
Ah, ok doing that…

**Comment by StephNelsonMTA** [comment]
Yep that was it! Beautiful. Thanks! Hopefully I can tackle other issues that arise here.

**Comment by StephNelsonMTA** [comment]
Morning:

I am now encountering an error which I believe is rooted in the changes with the getter/setter methods. I’ve revised my code according to the new documentation (removed the .get) but I keep receiving this error:

“TypeError: 'str' object is not callable”

I’ve uninstalled and reinstalled arcpy_metadata a couple times now and to no avail.

The rest of my code is working fine.

If you have a minute to help out that would be much appreciated!

Thanks,
Steph


From: Nelson, Steph
Sent: Monday, August 15, 2016 11:11 AM
To: 'ucd-cws/arcpy_metadata' <reply@reply.github.com>; ucd-cws/arcpy_metadata <arcpy_metadata@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [ucd-cws/arcpy_metadata] update init file (#21)

Yep that was it! Beautiful. Thanks! Hopefully I can tackle other issues that arise here.

**Comment by thomas-maschler** [comment]
Yes, at one point I made changes to the API which are not backwards compatible and will break existing code (getter/ setter methods)
Can you provide some sample code on point out where exactly it breaks?

Thanks,

Thomas

**Comment by nickrsan** [comment]
I'll also add that if you need to use older code, you can get the latest release in each point version from here: https://pypi.python.org/pypi/arcpy_metadata - updating the code is naturally the best option since Thomas' refactor made a lot of things much nicer, but if you need an older version to just make some existing code work, it's available.

**Comment by StephNelsonMTA** [comment]
Thanks. The code seems to break at purpose = metadata.purpose().

sds = "C:\\Users\\snelson\\AppData\\Roaming\\ESRI\\Desktop10.3\\ArcCatalog\\MTA spatial data store - READ ONLY.sde"
arcpy.env.workspace = sds
# outputFolder = "\\sfgis-svc.sfgov.org\\mta\\pub\\xmls"


datasets = arcpy.ListDatasets('','Feature')

for data in datasets:
    fcs = arcpy.ListFeatureClasses('','',data)
    for fc in fcs:
        # Extract the metadata
        fc_path = os.path.join(sds,data,fc)
        metadata = md.MetadataEditor(fc_path)
        purpose = metadata.purpose()

**Comment by nickrsan** [comment]
Hi Steph,

I know you provided the error above, but could you provide the full traceback? If the error is in arcpy_metadata, it will help us trace down where that's occurring. Thank you!

**Comment by StephNelsonMTA** [comment]
Sure:

Traceback (most recent call last):
  File "G:/03_Geodata/DatabaseAdministration/scripts/ListAllMetadata_dbg.py", line 25, in <module>
    purpose = metadata.purpose()
TypeError: 'str' object is not callable

Process finished with exit code -2146234327

**Comment by nickrsan** [comment]
Haha - great - I know it seems silly for such a small traceback, but it did make it finally click. The line should just be 

`purpose = metadata.purpose`

purpose is just an attribute now (at least as far as anyone using the code is concerned). Sorry for not catching that sooner!

**Comment by StephNelsonMTA** [comment]
Oh dang! So easy. Ack. Can’t believe I missed that! Thanks again.

**Comment by StephNelsonMTA** [comment]
Hi again:

Do you have recommendations for how to identify the author of a shapefile or .mxd in the wild using python in a Windows environment? Arcpy isn’t helpful for this where people haven’t filled in the “author” field in the mxd’s metadata. I have been poking around and trying various options culled from an internet search to no avail.

-Steph

**Comment by thomas-maschler** [comment]
You can either use the win32 module
http://timgolden.me.uk/python/win32_how_do_i/get-the-owner-of-a-file.html

or use standard batch command a batch command run in a python subprocess
http://stackoverflow.com/questions/19244735/what-is-the-batch-command-to-find-out-the-author-of-a-file

However, this will be a windows user, not a real person. If you don’t use an organizational domain, the information will be probably meaningless

**Pull request merged**
